use crate::{backend::Backend, num::Num, tensor::Tensor};

#[derive(Clone)]
pub enum Op<B: Backend, T: Num> {
    Reshape(Tensor<B, T>),
    PermutedAxes(Tensor<B, T>, Vec<usize>),
    Cat(Vec<Tensor<B, T>>, usize, Vec<usize>),
    BroadcastTo(Tensor<B, T>),
    GetItem(Tensor<B, T>, Vec<(usize, usize)>),
    Contiguous(Tensor<B, T>),
    Sum(Tensor<B, T>),
    SumAxis(Tensor<B, T>),
    Max(Tensor<B, T>, Tensor<B, T>),
    MaxAxis(Tensor<B, T>, Tensor<B, T>),
    Add(Tensor<B, T>, Tensor<B, T>),
    Sub(Tensor<B, T>, Tensor<B, T>),
    Mul(Tensor<B, T>, Tensor<B, T>),
    Div(Tensor<B, T>, Tensor<B, T>),
    Neg(Tensor<B, T>),
    Matmul(Tensor<B, T>, Tensor<B, T>),
    Pow(Tensor<B, T>, Tensor<B, T>),
    Sin(Tensor<B, T>),
    Cos(Tensor<B, T>),
    Tanh(Tensor<B, T>),
    Sqrt(Tensor<B, T>),
    Exp(Tensor<B, T>),
    Ln(Tensor<B, T>),
    Gather(Tensor<B, T>, Tensor<B, u32>, usize),
    IndexSelect(Tensor<B, T>, Tensor<B, u32>, usize),
    Im2col {
        x: Tensor<B, T>,
        out_h: usize,
        out_w: usize,
        fil_h: usize,
        fil_w: usize,
        stride_h: usize,
        stride_w: usize,
    },
    Col2im {
        x: Tensor<B, T>,
        in_h: usize,
        in_w: usize,
        fil_h: usize,
        fil_w: usize,
        stride_h: usize,
        stride_w: usize,
    },
    ZeroPadding2d(Tensor<B, T>, usize, usize),
}
